# Generated by scale-engine governance pack: project-scaffold@2
# Edit policy: prefer editing the pack in scale-engine; local overrides should be documented.

$ErrorActionPreference = 'Stop'

function Invoke-Scale {
  param([string[]]$ScaleArgs)

  if (Get-Command scale -ErrorAction SilentlyContinue) {
    & scale @ScaleArgs
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    return
  }

  & npx @hongmaple0820/scale-engine@0.21.2 @ScaleArgs
  if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
}

[Console]::Error.WriteLine("[scale-engine] compatibility wrapper: scripts/workflow/explore.ps1 -> scale skill scan")
$scaleArgs = @('skill', 'scan') + $args
Invoke-Scale -ScaleArgs $scaleArgs
